services:
  - type: worker
    name: MatchTrackerBotWorker
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node bot.js
    autoDeploy: true
    repo: https://github.com/Fizz1eOut/MatchTrackerBot
